"""initial_schema

Revision ID: c2f2eb6d372d
Revises:
Create Date: 2026-05-02 17:30:50.299160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "c2f2eb6d372d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("role", sa.Enum("client", "gestionnaire", "superviseur", "admin", name="roleenum"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("km", sa.Integer(), nullable=False),
        sa.Column("moteur", sa.Enum("essence", "diesel", "hybride", "electrique", name="moteurenum"), nullable=False),
        sa.Column("prix", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("lld", sa.Boolean(), nullable=False),
        sa.Column("mensualite", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("img", sa.Text(), nullable=False),
        sa.Column("spec_carburant", sa.String(length=100), nullable=False),
        sa.Column("spec_boite", sa.String(length=100), nullable=False),
        sa.Column("spec_couleur", sa.String(length=100), nullable=False),
        sa.Column("spec_places", sa.Integer(), nullable=False),
        sa.Column("spec_puissance", sa.String(length=50), nullable=False),
        sa.Column("visible_catalogue", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_id"), "vehicles", ["id"], unique=False)
    op.create_index(op.f("ix_vehicles_make"), "vehicles", ["make"], unique=False)
    op.create_index(op.f("ix_vehicles_model"), "vehicles", ["model"], unique=False)
    op.create_table(
        "dossiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=30), nullable=False),
        sa.Column("type", sa.Enum("achat", "lld", name="dossiertypeenum"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("brouillon", "depose", "en_instruction", "valide", "rejete", "annule", name="dossierstatusenum"),
            nullable=False,
        ),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("gestionnaire_id", sa.Integer(), nullable=True),
        sa.Column("motif_rejet", sa.Text(), nullable=True),
        sa.Column("notes_internes", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestionnaire_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dossiers_client_id"), "dossiers", ["client_id"], unique=False)
    op.create_index(op.f("ix_dossiers_id"), "dossiers", ["id"], unique=False)
    op.create_index(op.f("ix_dossiers_reference"), "dossiers", ["reference"], unique=True)
    op.create_index(op.f("ix_dossiers_status"), "dossiers", ["status"], unique=False)
    op.create_index(op.f("ix_dossiers_vehicle_id"), "dossiers", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("surcharge", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_options_vehicle_id"), "vehicle_options", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_photos_vehicle_id"), "vehicle_photos", ["vehicle_id"], unique=False)
    op.create_table(
        "dossier_historique",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("ancien_status", sa.String(length=30), nullable=True),
        sa.Column("nouveau_status", sa.String(length=30), nullable=False),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column("operateur_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossiers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["operateur_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dossier_historique_dossier_id"), "dossier_historique", ["dossier_id"], unique=False)
    op.create_table(
        "pieces_justificatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("type_piece", sa.String(length=50), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pieces_justificatives_dossier_id"), "pieces_justificatives", ["dossier_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pieces_justificatives_dossier_id"), table_name="pieces_justificatives")
    op.drop_table("pieces_justificatives")
    op.drop_index(op.f("ix_dossier_historique_dossier_id"), table_name="dossier_historique")
    op.drop_table("dossier_historique")
    op.drop_index(op.f("ix_vehicle_photos_vehicle_id"), table_name="vehicle_photos")
    op.drop_table("vehicle_photos")
    op.drop_index(op.f("ix_vehicle_options_vehicle_id"), table_name="vehicle_options")
    op.drop_table("vehicle_options")
    op.drop_index(op.f("ix_dossiers_vehicle_id"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_status"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_reference"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_id"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_client_id"), table_name="dossiers")
    op.drop_table("dossiers")
    op.drop_index(op.f("ix_vehicles_model"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_make"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(text("DROP TYPE IF EXISTS dossierstatusenum CASCADE"))
        op.execute(text("DROP TYPE IF EXISTS dossiertypeenum CASCADE"))
        op.execute(text("DROP TYPE IF EXISTS moteurenum CASCADE"))
        op.execute(text("DROP TYPE IF EXISTS roleenum CASCADE"))
    # ### end Alembic commands ###
